name: predTED
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.3
  - attrs=24.3.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - conda=25.3.1
  - conda-build=25.4.2
  - conda-index=0.6.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - distro=1.9.0
  - evalidate=2.0.3
  - expat=2.7.1
  - filelock=3.17.0
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozendict=2.4.2
  - gmp=6.3.0
  - gsl=2.7.1
  - icu=73.1
  - idna=3.7
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libiconv=1.16
  - liblief=0.16.4
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mbedtls=3.5.1
  - menuinst=2.2.0
  - mpfr=4.2.1
  - msgpack-python=1.0.3
  - mysql=8.4.0
  - ncurses=6.4
  - nlohmann_json=3.11.2
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - patch=2.7.6
  - patchelf=0.17.2
  - pcre2=10.42
  - perl=5.38.2
  - pillow=11.1.0
  - pip=25.1
  - pkginfo=1.12.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - psutil=5.9.0
  - pthread-stubs=0.3
  - py-lief=0.16.4
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-libarchive-c=5.1
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - referencing=0.30.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rpds-py=0.22.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=72.1.0
  - simdjson=3.10.1
  - sip=6.10.0
  - six=1.17.0
  - soupsieve=2.5
  - spdlog=1.11.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - truststore=0.10.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - viennarna==2.7.0
prefix: /home/mescalin/yseitz/miniconda3/envs/predTED
